### ISSUE TITLE
demo todo

### ISSUE THREAD

**Issue by mkolehmainen** [org-zpr/zpr-core#352]
- [x] add adapter tables (Chris is posting a review soon) #226
- [x] packet compression/expansion #364
- [x] add basic bind request/response (just drop initial packet) #363
- [x] add "node" operating mode of PH (we have all the pieces in place now)
- [x] add node-mode "forwarding" (just forward blindly between two adapters)
- [x] add DFTs (Dock Forwarding Table) for each Docking Session
- [x] extend bind request/response to node (enter PEPs into DFT)
- [x] hack ingress adapter->node bind request to create a FT entry and initiate a node->egress adapter bind request
- [x] integrate KM to PH (org-zpr/zpr-core#339 -> org-zpr/zpr-core#353)

**Comment by cpacejo** [comment]
https://github.com/org-zpr/zpr-core/milestone/1

**Comment by cpacejo** [comment]
I… think this is complete???
